name: safari_39
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - argcomplete=3.6.2=pyhd8ed1ab_0
  - binutils_impl_linux-64=2.43=h4bf12b8_4
  - bioconductor-apeglm=1.24.0=r43hf17093f_1
  - bioconductor-biobase=2.62.0=r43ha9d7317_3
  - bioconductor-biocgenerics=0.48.1=r43hdfd78af_2
  - bioconductor-biocparallel=1.36.0=r43hf17093f_2
  - bioconductor-data-packages=20250401=hdfd78af_0
  - bioconductor-delayedarray=0.28.0=r43ha9d7317_2
  - bioconductor-deseq2=1.42.0=r43hf17093f_2
  - bioconductor-edger=4.0.16=r43hf17093f_1
  - bioconductor-genomeinfodb=1.38.1=r43hdfd78af_1
  - bioconductor-genomeinfodbdata=1.2.11=r43hdfd78af_1
  - bioconductor-genomicranges=1.54.1=r43ha9d7317_2
  - bioconductor-iranges=2.36.0=r43ha9d7317_2
  - bioconductor-limma=3.58.1=r43ha9d7317_1
  - bioconductor-matrixgenerics=1.14.0=r43hdfd78af_3
  - bioconductor-s4arrays=1.2.0=r43ha9d7317_2
  - bioconductor-s4vectors=0.40.2=r43ha9d7317_2
  - bioconductor-sparsearray=1.2.2=r43ha9d7317_2
  - bioconductor-summarizedexperiment=1.32.0=r43hdfd78af_0
  - bioconductor-xvector=0.42.0=r43ha9d7317_2
  - bioconductor-zlibbioc=1.48.0=r43ha9d7317_2
  - bwidget=1.10.1=ha770c72_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - cffi=1.17.1=py312h06ac9bb_0
  - curl=8.13.0=h332b0f4_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=15.1.0=h4393ad2_2
  - gfortran_impl_linux-64=15.1.0=h3b9cdf2_2
  - graphite2=1.3.13=h59595ed_1003
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=15.1.0=h6a1bac1_2
  - harfbuzz=11.2.1=h3beb420_0
  - icu=75.1=he02047a_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jq=1.7.1=hd590300_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcurl=8.13.0=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-devel_linux-64=15.1.0=h4c094af_102
  - libgcc-ng=15.1.0=h69a702a_2
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran-ng=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libglib=2.84.2=h3618099_0
  - libgomp=15.1.0=h767d61c_2
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.47=h943b412_0
  - libsanitizer=15.1.0=h97b714f_2
  - libsqlite=3.49.2=hee588c1_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-devel_linux-64=15.1.0=h4c094af_102
  - libstdcxx-ng=15.1.0=h4852527_2
  - libtiff=4.7.0=hf01ce69_5
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - make=4.4.1=hb9d3cd8_2
  - markupsafe=3.0.2=py312h178313f_1
  - ncurses=6.5=h2d0b736_3
  - oniguruma=6.9.10=hb9d3cd8_0
  - openssl=3.5.0=h7b32b05_1
  - pandoc=3.7.0.1=ha770c72_0
  - pango=1.56.3=h9ac818e_1
  - pcre2=10.45=hc749103_0
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.0=h29eaf8c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - python=3.12.10=h9e4cc4f_0_cpython
  - python_abi=3.12=7_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h178313f_2
  - r-abind=1.4_5=r43hc72bb7e_1006
  - r-ashr=2.2_63=r43h93ab643_2
  - r-askpass=1.2.1=r43h2b5f3a1_0
  - r-assertthat=0.2.1=r43hc72bb7e_5
  - r-backports=1.5.0=r43hb1dbf0f_1
  - r-base=4.3.3=h65010dc_18
  - r-base64enc=0.1_3=r43hb1dbf0f_1007
  - r-bbmle=1.0.25.1=r43hc72bb7e_1
  - r-bdsmatrix=1.3_7=r43h2b5f3a1_2
  - r-bh=1.87.0_1=r43hc72bb7e_0
  - r-bit=4.6.0=r43h2b5f3a1_0
  - r-bit64=4.6.0_1=r43h2b5f3a1_0
  - r-bitops=1.0_9=r43h2b5f3a1_0
  - r-blob=1.2.4=r43hc72bb7e_2
  - r-broom=1.0.8=r43hc72bb7e_0
  - r-bslib=0.9.0=r43hc72bb7e_0
  - r-cachem=1.1.0=r43hb1dbf0f_1
  - r-callr=3.7.6=r43hc72bb7e_1
  - r-cellranger=1.1.0=r43hc72bb7e_1007
  - r-cli=3.6.5=r43h93ab643_0
  - r-clipr=0.8.0=r43hc72bb7e_3
  - r-coda=0.19_4.1=r43hc72bb7e_1
  - r-codetools=0.2_20=r43hc72bb7e_1
  - r-colorspace=2.1_1=r43hdb488b9_0
  - r-conflicted=1.2.0=r43h785f33e_2
  - r-cpp11=0.5.2=r43h785f33e_1
  - r-crayon=1.5.3=r43hc72bb7e_1
  - r-curl=6.2.2=r43h2700575_0
  - r-data.table=1.17.2=r43he23165d_0
  - r-dbi=1.2.3=r43hc72bb7e_1
  - r-dbplyr=2.5.0=r43hc72bb7e_1
  - r-digest=0.6.37=r43h0d4f4ea_0
  - r-dplyr=1.1.4=r43h0d4f4ea_1
  - r-dtplyr=1.3.1=r43hc72bb7e_2
  - r-ellipsis=0.3.2=r43hb1dbf0f_3
  - r-emdbook=1.3.13=r43hc72bb7e_1
  - r-etrunct=0.1=r43hc72bb7e_1006
  - r-evaluate=1.0.3=r43hc72bb7e_0
  - r-fansi=1.0.6=r43hb1dbf0f_1
  - r-farver=2.1.2=r43ha18555a_1
  - r-fastmap=1.2.0=r43ha18555a_1
  - r-fontawesome=0.5.3=r43hc72bb7e_0
  - r-forcats=1.0.0=r43hc72bb7e_2
  - r-formatr=1.14=r43hc72bb7e_2
  - r-fs=1.6.6=r43h93ab643_0
  - r-futile.logger=1.4.3=r43hc72bb7e_1006
  - r-futile.options=1.0.1=r43hc72bb7e_1005
  - r-gargle=1.5.2=r43h785f33e_1
  - r-generics=0.1.4=r43hc72bb7e_0
  - r-ggplot2=3.5.2=r43hc72bb7e_0
  - r-glue=1.8.0=r43h2b5f3a1_0
  - r-googledrive=2.1.1=r43hc72bb7e_2
  - r-googlesheets4=1.1.1=r43h785f33e_2
  - r-gtable=0.3.6=r43hc72bb7e_0
  - r-haven=2.5.4=r43h0d4f4ea_1
  - r-highr=0.11=r43hc72bb7e_1
  - r-hms=1.1.3=r43hc72bb7e_2
  - r-htmltools=0.5.8.1=r43ha18555a_1
  - r-httr=1.4.7=r43hc72bb7e_1
  - r-ids=1.0.1=r43hc72bb7e_4
  - r-invgamma=1.1=r43hc72bb7e_4
  - r-irlba=2.3.5.1=r43h0d28552_3
  - r-isoband=0.2.7=r43ha18555a_3
  - r-jquerylib=0.1.4=r43hc72bb7e_3
  - r-jsonlite=2.0.0=r43h2b5f3a1_0
  - r-knitr=1.50=r43hc72bb7e_0
  - r-labeling=0.4.3=r43hc72bb7e_1
  - r-lambda.r=1.2.4=r43hc72bb7e_4
  - r-lattice=0.22_7=r43h2b5f3a1_0
  - r-lifecycle=1.0.4=r43hc72bb7e_1
  - r-locfit=1.5_9.12=r43h2b5f3a1_0
  - r-lubridate=1.9.4=r43h2b5f3a1_0
  - r-magrittr=2.0.3=r43hb1dbf0f_3
  - r-mass=7.3_60.0.1=r43hb1dbf0f_1
  - r-matrix=1.6_5=r43he966344_1
  - r-matrixstats=1.5.0=r43h2b5f3a1_0
  - r-memoise=2.0.1=r43hc72bb7e_3
  - r-mgcv=1.9_3=r43h2ae2be5_0
  - r-mime=0.13=r43h2b5f3a1_0
  - r-mixsqp=0.3_54=r43hb79369c_3
  - r-modelr=0.1.11=r43hc72bb7e_2
  - r-munsell=0.5.1=r43hc72bb7e_1
  - r-mvtnorm=1.3_3=r43h9ad1c49_0
  - r-nlme=3.1_168=r43hb67ce94_0
  - r-numderiv=2016.8_1.1=r43hc72bb7e_6
  - r-openssl=2.3.2=r43he8289e2_0
  - r-pillar=1.10.2=r43hc72bb7e_0
  - r-pkgconfig=2.0.3=r43hc72bb7e_4
  - r-plyr=1.8.9=r43ha18555a_1
  - r-prettyunits=1.2.0=r43hc72bb7e_1
  - r-processx=3.8.6=r43h2b5f3a1_0
  - r-progress=1.2.3=r43hc72bb7e_1
  - r-ps=1.9.1=r43h2b5f3a1_0
  - r-purrr=1.0.4=r43h2b5f3a1_0
  - r-r6=2.6.1=r43hc72bb7e_0
  - r-ragg=1.4.0=r43hdcc764c_0
  - r-rappdirs=0.3.3=r43hb1dbf0f_3
  - r-rcolorbrewer=1.1_3=r43h785f33e_3
  - r-rcpp=1.0.14=r43h93ab643_0
  - r-rcpparmadillo=14.4.2_1=r43hc2d650c_0
  - r-rcppeigen=0.3.4.0.2=r43hb79369c_0
  - r-rcppnumerical=0.6_0=r43h0d4f4ea_1
  - r-rcurl=1.98_1.16=r43he8228da_1
  - r-readr=2.1.5=r43h0d4f4ea_1
  - r-readxl=1.4.5=r43h328fee5_0
  - r-rematch=2.0.0=r43hc72bb7e_1
  - r-rematch2=2.1.2=r43hc72bb7e_4
  - r-reprex=2.1.1=r43hc72bb7e_1
  - r-rlang=1.1.6=r43h93ab643_0
  - r-rmarkdown=2.29=r43hc72bb7e_0
  - r-robustrankaggreg=1.2.1=r43hc72bb7e_3
  - r-rstudioapi=0.17.1=r43hc72bb7e_0
  - r-rvest=1.0.4=r43hc72bb7e_1
  - r-sass=0.4.10=r43h93ab643_0
  - r-scales=1.4.0=r43hc72bb7e_0
  - r-selectr=0.4_2=r43hc72bb7e_4
  - r-snow=0.4_4=r43hc72bb7e_3
  - r-squarem=2021.1=r43hc72bb7e_3
  - r-statmod=1.5.0=r43ha36c22a_2
  - r-stringi=1.8.7=r43h3c328a7_0
  - r-stringr=1.5.1=r43h785f33e_1
  - r-sys=3.4.3=r43h2b5f3a1_0
  - r-systemfonts=1.2.3=r43h5c043a3_0
  - r-textshaping=1.0.1=r43h16f7c1a_0
  - r-tibble=3.2.1=r43hdb488b9_3
  - r-tidyr=1.3.1=r43h0d4f4ea_1
  - r-tidyselect=1.2.1=r43hc72bb7e_1
  - r-tidyverse=2.0.0=r43h785f33e_2
  - r-timechange=0.3.0=r43ha18555a_1
  - r-tinytex=0.57=r43hc72bb7e_0
  - r-truncnorm=1.0_9=r43h2b5f3a1_4
  - r-tzdb=0.5.0=r43h93ab643_0
  - r-utf8=1.2.5=r43h2b5f3a1_0
  - r-uuid=1.2_1=r43hdb488b9_0
  - r-vctrs=0.6.5=r43h0d4f4ea_1
  - r-viridislite=0.4.2=r43hc72bb7e_2
  - r-vroom=1.6.5=r43h0d4f4ea_1
  - r-withr=3.0.2=r43hc72bb7e_0
  - r-xfun=0.52=r43h93ab643_0
  - r-xml2=1.3.8=r43h1bb2df6_0
  - r-yaml=2.3.10=r43hdb488b9_0
  - readline=8.2=h8c095d6_2
  - rpy2=3.5.11=py312r43hc7c0aa3_3
  - sed=4.9=h6688a6e_0
  - setuptools=80.8.0=pyhff2d567_0
  - simplegeneric=0.8.1=pyhd8ed1ab_2
  - sysroot_linux-64=2.17=h0157908_18
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h8bc8fbc_6
  - toml=0.10.2=pyhd8ed1ab_1
  - tomlkit=0.13.2=pyha770c72_1
  - tzdata=2025b=h78e105d_0
  - tzlocal=5.3=py312h7900ff3_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xmltodict=0.14.2=pyhd8ed1ab_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - yq=3.4.3=pyhd8ed1ab_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.2.2
      - adpbulk==0.1
      - anndata==0.8.0
      - antlr4-python3-runtime==4.9.3
      - blosc2==3.3.4
      - certifi==2025.4.26
      - chardet==5.2.0
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpickle==3.1.1
      - colorlog==6.9.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - daemonize==2.5.0
      - debugpy==1.8.14
      - distlib==0.3.9
      - et-xmlfile==2.0.0
      - filelock==3.18.0
      - fonttools==4.58.0
      - fsspec==2025.5.1
      - grpcio==1.71.0
      - h5py==3.13.0
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.2.0
      - idna==3.10
      - iniconfig==2.1.0
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - llvmlite==0.44.0
      - markdown==3.8
      - matplotlib==3.6.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      - narwhals==1.40.0
      - natsort==8.4.0
      - ndindex==1.10.0
      - networkx==3.4.2
      - numba==0.61.2
      - numexpr==2.10.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==1.3.4
      - patsy==1.0.1
      - pillow==11.2.1
      - pkginfo==1.12.1.2
      - platformdirs==4.3.8
      - plotly==6.1.1
      - pluggy==1.6.0
      - protobuf==4.25.7
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - requests==2.32.3
      - scanpy==1.9.1
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - session-info==1.0.1
      - six==1.17.0
      - statannotations==0.7.2
      - statsmodels==0.14.1
      - stdlib-list==0.11.1
      - submitit==1.5.3
      - sympy==1.14.0
      - tables==3.10.2
      - tabview==1.4.4
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - torch==2.7.0
      - tqdm==4.67.1
      - triton==3.3.0
      - typing-extensions==4.13.2
      - umap-learn==0.5.7
      - urllib3==2.4.0
      - virtualenv==20.31.2
      - werkzeug==3.1.3
      - xgboost==3.0.2
      - xlsxwriter==3.2.3
